name: Terraform RDS Deployment

on:
  workflow_dispatch:   # Manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rds   # Folder with your rds.tf

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2   # Use your preferred version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform changes
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve
